# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '12.0'
prepare_react_native_project!

# Remove the linkage custom configuration and use a standard approach
use_frameworks! :linkage => :static

target 'MealRatingAppNew' do
  config = use_native_modules!

  # Remove the static framework setting
  # $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  # Instead of individual Firebase components with modular headers,
  # use the standard Firebase pods
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'

  # Add React Native Maps and Google Maps for iOS
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'GoogleMaps'
  
  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
